#!/bin/sh
while read file
do
        case "$1" in
        "w") setbg "$file" & ;;
        "r") convert -rotate 90 "$file" "$file" ;;
	    "R") convert -rotate -90 "$file" "$file" ;;
	    "f") convert -flop "$file" "$file" ;;
	    "y")
		        echo -n "$file" | tr -d '\n' | xclip -selection clipboard &&
		        notify-send "$file copied to clipboard" & ;;
	    "Y")
		        readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			    notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	    "d")
		        [ "$(printf "No\\nYes" | rofi -config ~/.config/rofi/themes/dmenu.rasi -dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
	    "g") setsid -f gimp "$file" ;;
        esac
done
